### PR TITLE
Update heapless, remove unneeded typenum dependency, and fix formatting as well as clippy warnings.

### PR DESCRIPTION
**Pull request by sosthene-nitrokey**

### CODE REVIEW

**Comment by t-moe** [comment]
@nickray Hey Nicolas,
Can you aprove/merge this? It would really help us going forward with our crates.

Thanks + Greetings from Bern

**Review by daringer — APPROVED** [review]

**Review by robin-nitrokey — APPROVED** [review]
LGTM, but please do not release 0.4.0 yet.  AFAIR there are still some changes I’d like to include.

**Comment by sosthene-nitrokey** [comment]
Yes, I want to remove the CBOR stuff (unused, and out of place). I also want remove the `Deref` impl, and maybe even remove `heapless` from the public API (outside of `From`/`To` features behind a `heapless-0-8` feature flag), so that we can bump heapless in the future without breaking changes.

**Comment by robin-nitrokey** [comment]
I also thought about removing the public heapless dependency.  But AFAIS we don’t have a way to support multiple heapless versions because heapless does not have a way to construct a vec from raw parts.

**Comment by sosthene-nitrokey** [comment]
I'll open an issue for that discussion

**Pull request merged**
